version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    depends_on:
      - db

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:8000

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: AM_APP
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: